#############################################################################
# Id: match-all.action,v
#
# This file contains the actions that are applied to all requests and
# may be overruled later on by other actions files. Less experienced
# users should only edit this file through the actions file editor.
#
# This file deviates from the normal Debian version of this file.  It
# has been modified for freedombox-privoxy.
#
#############################################################################
{ \
+change-x-forwarded-for{block} \
+client-header-tagger{css-requests} \
+client-header-tagger{image-requests} \
+hide-from-header{block} \
+filter{webbugs} \
+filter{jumping-windows} \
+set-image-blocker{blank} \
}
/ # Match all URLs
